### ISSUE TITLE
RUX-Timeline

### ISSUE THREAD

**Issue by ShaurCapella** [RocketCommunicationsInc/astro-components#17]
Was wondering when the RUX-Timeline might have documentation to accompany how to use it - am trying to use it in a quasar/vue based webpage for a proof a concept/learning project but have no idea how to use the component atm

**Comment by charlesabarnes** [comment]
I don't have all of the answers necessary, but I can provide an object that should work to generate the timeline and associated data.   Please let me know if you have any questions about this.

```
[
      {
        label: 'Track Label',
        regions: [{
          startTime: start date of timeline "region,
          endTime: end date of timeline "region",
          label: 'label of timeline "region"',
          status: timeline "region" icon corresponding to [what's found in the status documentation](https://astro-components.netlify.app/?path=/story/components-status--status),
        }]
      }
]
```

**Comment by markacianfrani** [comment]
@ShaurCapella sorry for the late reply here. the timeline component was more of a single-use component. we're currently planning to deprecate and refactor it into more useable, easily-documented, components.
