### ISSUE TITLE
rux-tree depends on rux-utils but it is not declared

### ISSUE THREAD

**Issue by moaxcp** [RocketCommunicationsInc/astro-components#170]
When adding `rux-tree` I got an error

```
This relative module was not found:

* ../rux-utils/data.js in ./node_modules/@astrouxds/rux-tree/rux-tree.js

```

To fix this I had to add `rux-utils` to my package.json. This should not be needed. `rux-tree` should declare `rux-utils` in its package.json.

**Comment by micahjones13** [comment]
A fix for this has been merged into our staging branch and will available in the next upcoming release. Thanks for bringing this up!
