### ISSUE TITLE
3 Digit Julian Date

### ISSUE THREAD

**Issue by Rachel-Platz** [RocketCommunicationsInc/astro-components#186]
I would like to view the Julian Date in the rux-clock so that it always shows 3 digits. Attached is a screenshot of the the current implementation from the astro storyboard where the clock's date only has 2 digits when it is less than 100. There is also a screenshot from juliandate.net to show that the day always has 3 digits and a link to IBM that shows that the Julian date format should be 3 digits.

IBM Link:
https://www.ibm.com/docs/en/cics-vt/2.1?topic=reengineering-converting-between-julian-gregorian-date-formats

![AstroStorybook RuxClock](https://user-images.githubusercontent.com/98778932/151872915-076ef5b3-918c-4449-adf8-380ec868c5f9.PNG)
![Juliandate](https://user-images.githubusercontent.com/98778932/151872927-b8b84d06-cd70-45a7-8042-17a9648b5558.PNG)

**Comment by dmcalester** [comment]
Thanks Rachel,

We have an internal ticket and adding this to our sprint that started today.

**Comment by dmcalester** [comment]
Resolved in 6.1.0 release https://github.com/RocketCommunicationsInc/astro/releases/tag/v6.1.0
